//
//  SutdaExp.swift
//  Sutda
//
//  Created by 유창현 on 2022/02/26.
//

import SwiftUI

struct SutdaExp: View {
    
    var body: some View {
        ScrollView {
            VStack {
                Group {
                    VStack {
                        HStack(spacing: 0) {
                            Image("1month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("2month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("3month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("4month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("5month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("6month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("7month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("8month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("9month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("10month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            }
                        HStack(spacing: 0) {
                            Image("1-1month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("2-1month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("3-1month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("4-1month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("5-1month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("6-1month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("7-1month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("8-1month")
                                    .resizable()
                                    .aspectRatio(contentMode: .fit)
                            Image("9-1month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            Image("10-1month")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                            }
                        }.padding()
                    
                    Text("섯다에서 사용되는 화투는 1월부터 10월까지의 패 각 두 장씩 모두 20 장입니다.")
                        .padding()
                    Text("이 20 장에서 두 장을 사용하여 족보를 만들어 베팅을 하게 됩니다.")
                        .padding()
                    
                    Text("족보 조합 설명")
                        .font(.largeTitle)
                        .fontWeight(.bold)
                        .padding()
                    Text("1 . 삼팔광땡")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("삼광과 팔광으로 이루어진 최강의 족보")
                        Spacer()
                        Image("3month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("8month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                    Text("2 . 광땡")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("일광과 삼광, 팔광과의 조합으로 일팔광땡이 일삼광땡보다 높음")
                        Spacer()
                        Image("1month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("3month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image("8month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                    Text("3 . 땡")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("같은 월의 조합, 장땡(10월)~삥땡(1월) 순으로 숫자가 높을수록 이김")
                        Spacer()
                        Image("10month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("10-1month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                }
                Group {
                    Text("4 . 알리")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("1월과 2월의 조합입니다")
                        Spacer()
                        Image("1month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("2month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                    Text("5 . 독사")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("1월과 4월의 조합입니다")
                        Spacer()
                        Image("1month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("4month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                    Text("6 . 구삥")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("1월과 9월의 조합입니다")
                        Spacer()
                        Image("1month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("9month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                    Text("7 . 장삥")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("1월과 10월의 조합입니다")
                        Spacer()
                        Image("1month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("10month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                    Text("8 . 장사")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("4월과 10월의 조합입니다")
                        Spacer()
                        Image("4month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("10month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                }
                Group {
                    Text("9 . 세륙")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("4월과 6월의 조합입니다")
                        Spacer()
                        Image("4month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("6month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                    Text("10 . 갑오")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("두 장의 숫자를 합한 수의 끝자리 숫자가 9인 경우")
                        Spacer()
                        Image("2month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("7month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                    Text("11 . 끗")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("끗수가 8 부터 1일 때 각각 8끗~1끗, 숫자가 높을수록 이김")
                        Spacer()
                        Image("1-1month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("8-1month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                    Text("12 . 망통")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("2월과 8월의 조합, 끗수가 0인 가장 낮은 족보")
                        Spacer()
                        Image("2month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("8month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                }
                Group {
                    Text("특수 족보 조합")
                        .font(.largeTitle)
                        .fontWeight(.bold)
                        .padding()
                    Text("땡잡이")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("3월과 7월의 조합, 구땡 이하의 족보를 이길 수 있지만 상대방 중 땡이 없다면 망통으로 계산")
                        Spacer()
                        Image("3month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("7month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                    Text("구사")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("4월과 9월의 조합, 상대방의 족보 중 가장 높은 것이 알리 이하이면 재경기 가능")
                        Spacer()
                        Image("4-1month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("9-1month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                    Text("멍텅구리 구사")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("열자리 4월과 열자리 9월의 조합, 상대방의 족보 중 가장 높은 것이 장땡 이하이면 재경기 가능")
                        Spacer()
                        Image("4month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("9month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                    Text("암행어사")
                        .font(.title)
                        .padding()
                    HStack(spacing: 0) {
                        Text("열자리 4월과 열자리 7월의 조합, 일삼광땡 또는 일팔광땡을 이김, 상대방 중 광땡이 없다면 1끗으로 계산")
                        Spacer()
                        Image("4month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                        Image(systemName: "plus")
                        Image("7month")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: 60)
                    }.padding()
                }
            }
        }
    }
}

struct SutdaExp_Previews: PreviewProvider {
    static var previews: some View {
        SutdaExp()
    }
}
